lib/plurimath/mathml.rb, lib/plurimath/mathml/constants.rb, lib/plurimath/mathml/parse.rb, spec/plurimath/mathml/parse_spec.rb
Added **```Parslet```** parse rules for parsing **```MathMl```** string
closes #14
=> added parslet parse rules for mathml string

lib/plurimath/math.rb, lib/plurimath/math/function/base.rb, lib/plurimath/math/function/fenced.rb, lib/plurimath/math/function/power.rb, lib/plurimath/math/function/power_base.rb, lib/plurimath/math/function/table.rb, lib/plurimath/math/function/td.rb, lib/plurimath/math/function/ternary_function.rb, lib/plurimath/math/function/tr.rb, lib/plurimath/math/function/underover.rb, lib/plurimath/mathml.rb, lib/plurimath/mathml/parser.rb, lib/plurimath/mathml/transform.rb, spec/plurimath/math/function/base_spec.rb, spec/plurimath/math/function/fenced_spec.rb, spec/plurimath/math/function/power_base_spec.rb, spec/plurimath/math/function/power_spec.rb, spec/plurimath/math/function/table_spec.rb, spec/plurimath/math/function/td_spec.rb, spec/plurimath/math/function/tr_spec.rb, spec/plurimath/math/function/underover_spec.rb, spec/plurimath/mathml/parser_spec.rb
Added transformation rules for **``syntax tree``**.
closes #15
=> Added transform rules for syntax tree

lib/plurimath/latex/constants.rb, lib/plurimath/latex/parse.rb, lib/plurimath/latex/parser.rb, lib/plurimath/latex/transform.rb, lib/plurimath/math/function.rb, lib/plurimath/math/function/bar.rb, lib/plurimath/math/function/left.rb, lib/plurimath/math/function/over.rb, lib/plurimath/math/function/right.rb, lib/plurimath/math/function/table.rb, lib/plurimath/math/function/table/align.rb, lib/plurimath/math/function/table/array.rb, lib/plurimath/math/function/table/bmatrix.rb, lib/plurimath/math/function/table/matrix.rb, lib/plurimath/math/function/table/multline.rb, lib/plurimath/math/function/table/pmatrix.rb, lib/plurimath/math/function/table/split.rb, lib/plurimath/math/function/table/vmatrix.rb, lib/plurimath/math/symbol.rb, spec/plurimath/latex/parse_spec.rb, spec/plurimath/latex/parser_spec.rb, spec/plurimath/math/formula/latex_spec.rb
Added ``` spec's ``` from ``` metanorma/attached-files ``` examples for latex.
closes #38
=> Latex parser enhancements

lib/plurimath/mathml/parse.rb, lib/plurimath/mathml/transform.rb, spec/plurimath/mathml/parser_spec.rb
Added **MathML** parser, transformation rules, and specs for symbols.
closes #65
=> Added mathml parser/transformation rules and specs for symbols

lib/plurimath/mathml/transform.rb, spec/plurimath/math/formula_spec.rb, spec/plurimath/mathml/parser_spec.rb
Fixed **Formula to Asciimath** conversion crash.
closes #72
=> Fixed failing Formula to Asciimath conversion

lib/plurimath/asciimath/constants.rb, lib/plurimath/asciimath/parse.rb, lib/plurimath/asciimath/transform.rb, lib/plurimath/math/formula.rb, lib/plurimath/math/function/base.rb, lib/plurimath/math/function/binary_function.rb, lib/plurimath/math/function/color.rb, lib/plurimath/math/function/font_style.rb, lib/plurimath/math/function/frac.rb, lib/plurimath/math/function/int.rb, lib/plurimath/math/function/lim.rb, lib/plurimath/math/function/log.rb, lib/plurimath/math/function/mod.rb, lib/plurimath/math/function/oint.rb, lib/plurimath/math/function/over.rb, lib/plurimath/math/function/power.rb, lib/plurimath/math/function/prod.rb, lib/plurimath/math/function/sum.rb, lib/plurimath/math/function/table.rb, lib/plurimath/math/function/td.rb, lib/plurimath/math/function/ternary_function.rb, lib/plurimath/math/function/unary_function.rb, lib/plurimath/utility.rb, spec/plurimath/asciimath/parser_spec.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/math/formula/mathml_spec.rb, spec/plurimath/math/formula_spec.rb, spec/plurimath/math/function/lim_spec.rb, spec/plurimath/math/function/power_base_spec.rb
Updated AsciiMath parser and transformation rules for new examples from **```asciidoctor/asciimath```**.
=> Updated parser and transformation rules for new asciimath examples

lib/plurimath/latex/constants.rb, lib/plurimath/latex/parse.rb, lib/plurimath/latex/transform.rb, spec/plurimath/latex_spec.rb
Fixed crash on latex text conversion.
closes #123
=> Fixed crash on latex text conversion

lib/plurimath/math/formula.rb, lib/plurimath/math/function/fenced.rb, lib/plurimath/math/function/font_style/bold.rb, lib/plurimath/math/function/font_style/double_struck.rb, lib/plurimath/math/function/font_style/fraktur.rb, lib/plurimath/math/function/font_style/italic.rb, lib/plurimath/math/function/font_style/monospace.rb, lib/plurimath/math/function/font_style/normal.rb, lib/plurimath/math/function/font_style/sans-serif.rb, lib/plurimath/math/function/font_style/script.rb, lib/plurimath/math/function/sum.rb, lib/plurimath/utility.rb, spec/plurimath/asciimath_spec.rb
Added safe operators in font style and other classes for empty content/values.
closes #130
=> Implemented & operator for AsciiMath font_styles

lib/plurimath/asciimath/transform.rb, lib/plurimath/latex/parse.rb, lib/plurimath/math/formula.rb, lib/plurimath/math/function/binary_function.rb, lib/plurimath/math/function/sum.rb, lib/plurimath/math/function/ternary_function.rb, lib/plurimath/math/function/unary_function.rb, lib/plurimath/math/symbol.rb, lib/plurimath/utility.rb, spec/plurimath/asciimath/asciidoctor_examples_spec.rb, spec/plurimath/asciimath/metanorma/mn_samples_bipm_spec.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/latex_spec.rb, spec/plurimath/math/formula_spec.rb
Updated **Parser** rule and **Transformation** method.
Added spec of example from #145 
closes #145
=> Updated latex parser rule for left right with unary function

lib/plurimath/math/function/table.rb, lib/plurimath/math/function/td.rb, lib/plurimath/omml/parser.rb, lib/plurimath/omml/transform.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/fixtures/047.omml, spec/plurimath/fixtures/066.omml, spec/plurimath/fixtures/067.omml, spec/plurimath/fixtures/070.omml, spec/plurimath/fixtures/156.omml, spec/plurimath/fixtures/157.omml, spec/plurimath/fixtures/158.omml, spec/plurimath/fixtures/159.omml, spec/plurimath/fixtures/160.omml, spec/plurimath/fixtures/161.omml, spec/plurimath/fixtures/162.omml, spec/plurimath/fixtures/163.omml, spec/plurimath/fixtures/168.omml, spec/plurimath/fixtures/169.omml, spec/plurimath/fixtures/170.omml, spec/plurimath/fixtures/171.omml, spec/plurimath/fixtures/172.omml, spec/plurimath/fixtures/173.omml, spec/plurimath/fixtures/174.omml, spec/plurimath/fixtures/175.omml, spec/plurimath/fixtures/176.omml, spec/plurimath/fixtures/177.omml, spec/plurimath/fixtures/issue-158.omml
This PR updates Table parsing, transformation, and conversion methods in **OMML**.
closes #164
=> Updated omml fixtures files, conversion, and parser methods

lib/plurimath/math/function/ternary_function.rb, lib/plurimath/mathml/parser.rb, lib/plurimath/mathml/transform.rb, lib/plurimath/omml/transform.rb, lib/plurimath/utility.rb, spec/plurimath/fixtures/022.omml, spec/plurimath/fixtures/023.omml, spec/plurimath/fixtures/024.omml, spec/plurimath/fixtures/034.omml, spec/plurimath/fixtures/035.omml, spec/plurimath/fixtures/036.omml, spec/plurimath/fixtures/037.omml, spec/plurimath/fixtures/038.omml, spec/plurimath/fixtures/039.omml, spec/plurimath/fixtures/045.omml, spec/plurimath/fixtures/046.omml, spec/plurimath/fixtures/047.omml, spec/plurimath/fixtures/048.omml, spec/plurimath/fixtures/180.omml, spec/plurimath/fixtures/expected_values.rb, spec/plurimath/latex_spec.rb, spec/plurimath/mathml/v3/section_3_spec.rb, spec/plurimath/mathml/v3/section_4_spec.rb
This PR updates OMML transform rules and implements rubocop fixes.
=> Rubocop and OMML transform fixes

lib/plurimath/math/function/text.rb, spec/plurimath/fixtures/033.omml, spec/plurimath/fixtures/047.omml, spec/plurimath/fixtures/070.omml, spec/plurimath/fixtures/126.omml, spec/plurimath/fixtures/133.omml, spec/plurimath/fixtures/134.omml, spec/plurimath/fixtures/issue-158.omml
This PR changes the encoding of Unicode from named to hexadecimal.
closes #183
=> Updated encoding from named to hexadecimal

lib/plurimath/math/function/text.rb, spec/plurimath/omml/parser_spec.rb, spec/plurimath/omml_spec.rb
Fixes Unicode letter errors in OMML
closes #189
=> fix: unicode letter in omml

lib/plurimath/math/symbol.rb
This PR removes unused condition in the MathML conversion function.
closes #198
=> Unicodes update for MathML

lib/plurimath/asciimath/transform.rb, lib/plurimath/math/function/text.rb, lib/plurimath/utility.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/html_spec.rb, spec/plurimath/integration/asciimath_spec.rb
This PR adds new transformation rules for AsciiMath to fix jcgm#35.
closes #195
=> AsciiMath Tranformation Rules 

lib/plurimath/unitsml.rb, spec/plurimath/unitsml_spec.rb
This PR updates regex for variable in **Power** in **UnitsML** expression.
Adds the valid values specs from the issue below.
closes #236
=> UnitsML expressions validations

lib/plurimath/asciimath/transform.rb, spec/plurimath/asciimath_spec.rb
This PR adds new **transformation rule** and spec for **AsciiMath**.
closes #227
=> Added new transformation rule for AsciiMath

lib/plurimath/asciimath/constants.rb, lib/plurimath/asciimath/parse.rb, lib/plurimath/math/symbols/paren/lfloor.rb, lib/plurimath/math/symbols/paren/rceil.rb, lib/plurimath/math/symbols/paren/rfloor.rb, lib/plurimath/math/symbols/prime.rb, lib/plurimath/math/symbols/sprime.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/math/symbols/paren/lfloor_spec.rb, spec/plurimath/math/symbols/paren/rceil_spec.rb, spec/plurimath/math/symbols/paren/rfloor_spec.rb
This PR updates AsciiMath parsing rules, constants, symbols files, and specs.
=> AsciiMath parsing and conversion

lib/plurimath/math/symbols/backslash.rb, lib/plurimath/utility.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/math/symbols/backslash_spec.rb
This PR updates the symbols file, specs, and updated symbols file loading methods.
=> AsciiMath backslash symbol

lib/plurimath/math/function/log.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/fixtures/mathml/line_break/line-break-061.mathml, spec/plurimath/latex_spec.rb
This PR fixes missing Log rendering and added/updated specs.
closes #265
=> Log rendering fix

lib/plurimath/formatter/number_formatter.rb, lib/plurimath/formatter/numbers/fraction.rb, lib/plurimath/formatter/numbers/significant.rb, lib/plurimath/formatter/numeric_formatter.rb, lib/plurimath/number_formatter.rb, spec/plurimath/number_formatter_spec.rb
This PR
1. Updates digit_count scenario
2. Adds support of the `significant:` option for significant numbers.
closes #264
=> Significant digits support

lib/plurimath/latex/parser.rb, spec/plurimath/latex/latexmath_aggregator_spec.rb, spec/plurimath/latex/parser_spec.rb, spec/plurimath/latex_spec.rb
This PR updates **LaTeX** input string processing for space removal in text functions.
closes #250
=> LaTeX input string processing

lib/plurimath/asciimath/parse.rb, lib/plurimath/asciimath/transform.rb, spec/plurimath/asciimath_spec.rb
This PR updates **AsciiMath**'s **parsing** and **transformation** rules and added specs.
closes metanorma/bipm-si-brochure#247
=> AsciiMath extra closing parenthesis parsing

lib/plurimath/mathml/parser.rb
This PR updates `require` and `configuration` of **Mml**.
closes #331
=> Rails app tests failing on GHA

lib/plurimath/math/core.rb, lib/plurimath/math/function/unitsml.rb, spec/plurimath/asciimath_spec.rb
This PR fixes the duplication of `Plurimath::Math::Function::Unitsml` instances.
closes #343
=> Fix: `Function::Unitsml` instances duplication

.github/workflows/dependent-repos-js.json, .github/workflows/dependent-repos-ruby.json, .github/workflows/dependent-repos.json, .github/workflows/dependent-tests.yml, .github/workflows/plurimath_js.yml
This PR adds support to trigger **Plurimath-JS** workflow from **Plurimath**.
closes #288
=> Plurimath-JS workflow automation

lib/plurimath/asciimath/parse.rb, lib/plurimath/math/function/table.rb, spec/plurimath/asciimath_spec.rb
This PR fixes/updates parsing rules for tables/matrices.
closes #379
=> fix: matrices parsing rule

lib/plurimath/latex/parse.rb, lib/plurimath/latex/transform.rb, lib/plurimath/math/symbols/three_per_em_space.rb, spec/plurimath/latex/parser_spec.rb, spec/plurimath/math/symbols/three_per_em_space_spec.rb, spec/plurimath/unicode_math/plurimath/unicodemath_tests_spec.rb, spec/plurimath/unicode_math/plurimath/unicodemath_transform_spec.rb, spec/spec_helper.rb
=> Rename semicolon space into three per em space
