lib/plurimath/math/formula.rb, lib/plurimath/math/function/binary_function.rb, lib/plurimath/math/function/int.rb, lib/plurimath/math/function/log.rb, lib/plurimath/math/function/mod.rb, lib/plurimath/math/function/oint.rb, lib/plurimath/math/function/prod.rb, lib/plurimath/math/function/sum.rb, lib/plurimath/math/function/text.rb, lib/plurimath/math/function/unary_function.rb, lib/plurimath/math/number.rb, lib/plurimath/math/symbol.rb, spec/plurimath/math/formula_spec.rb
Added **`to_asciimath`** method in all `function` files to convert ruby formula back to `Asciimath` string.
closes #9
=> Formula to asciimath

lib/plurimath/html.rb, lib/plurimath/html/constants.rb, lib/plurimath/html/parse.rb, spec/plurimath/html/parse_spec.rb
Added parser for parsing **``` HTML ```** string to the syntax tree.
closes #43
=> Added parslet parse rules for HTML string

lib/plurimath/html/parser.rb, lib/plurimath/html/transform.rb, lib/plurimath/math.rb, spec/plurimath/html/parser_spec.rb
Added **```HTML transformation ```** rules for the ``` syntax tree ```.
closes #44
=> Added Html transformation rules for syntax tree

lib/plurimath/html/constants.rb, lib/plurimath/math/formula.rb, lib/plurimath/math/function/base.rb, lib/plurimath/math/function/binary_function.rb, lib/plurimath/math/function/log.rb, lib/plurimath/math/function/mod.rb, lib/plurimath/math/function/power.rb, lib/plurimath/math/function/power_base.rb, lib/plurimath/math/function/prod.rb, lib/plurimath/math/function/sum.rb, lib/plurimath/math/function/table.rb, lib/plurimath/math/function/td.rb, lib/plurimath/math/function/ternary_function.rb, lib/plurimath/math/function/text.rb, lib/plurimath/math/function/tr.rb, lib/plurimath/math/function/unary_function.rb, lib/plurimath/math/number.rb, lib/plurimath/math/symbol.rb, spec/plurimath/html_spec.rb, spec/plurimath/math/formula/html_spec.rb
Added functions for reverse conversion from **``` Plurimath::Math::Formula ```** to **``` HTML ```**.
closes #30
=> Added formula to HTML conversion spec's and functions in files

lib/plurimath/latex/parse.rb, lib/plurimath/latex/transform.rb, lib/plurimath/math/function/left.rb, lib/plurimath/math/function/unary_function.rb, lib/plurimath/math/symbol.rb, lib/plurimath/mathml/constants.rb, lib/plurimath/omml/transform.rb, lib/plurimath/utility.rb, spec/plurimath/latex/parse_spec.rb, spec/plurimath/latex/parser_spec.rb, spec/plurimath/latex_spec.rb, spec/plurimath/math/formula/mathml_spec.rb, spec/plurimath/math/formula_spec.rb, spec/plurimath/mathml/parser_spec.rb
Updated **MathML** conversion methods and **Latex Parser** and **Transformation** rules.
.
closes #60
=> Mathml and latex parser/transformation rules fixes

lib/plurimath/mathml/parse.rb, spec/plurimath/mathml/parser_spec.rb
Updated **MathML** parser rule and added spec for decimal numbers(separated by comma and dot).
closes #64
=> Updated mathml parser rule and added specs for decimal numeric values

lib/plurimath/latex/parse.rb, lib/plurimath/latex/parser.rb, spec/plurimath/latex/metanorma_examples_spec.rb
Implemented fixes for latex-math examples from adoc files.
closes #118
=> Plurimath LaTeX adoc files examples

lib/plurimath/asciimath/parse.rb, lib/plurimath/latex/constants.rb, spec/plurimath/asciimath_spec.rb
Resolved an issue with parsing **AsciiMath** where the presence of a **single double quote** caused a crash.
closes #121
=> Fixed missing closing double quote crash

lib/plurimath/asciimath/transform.rb, spec/plurimath/asciimath_spec.rb
Added **Parslet** transformation rule for empty text in **AsciiMath** formula.
closes #127
=> Added text transformation rule for asciimath formula

lib/plurimath/math.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/math_spec.rb
Updated the code to catch **Parslet**'s exception on parsing or conversion failure for **Plurimath**, and instead of raising the exception, added a **Plurimath** exception.
=> Added Plurimath error message support

lib/plurimath/asciimath/transform.rb, lib/plurimath/math/symbol.rb, lib/plurimath/utility.rb, spec/plurimath/asciimath/asciidoctor_examples_spec.rb, spec/plurimath/asciimath/metanorma/mn_samples_bipm_spec.rb, spec/plurimath/asciimath_spec.rb
1. Updated vertical bar MathML conversion.
a. closes #144 
2. Added support for explicitly provided parenthesis and exponent expression parenthesis.
a. closes #143 
b. closes #146
=> AsciiMath transformation rules and utility method

lib/plurimath/math/function/tilde.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/math/function/tilde_spec.rb
This pull request addresses an issue with the `tilde(x)` example representation in the **AsciiMath** to **MathML** conversion.
closes #150
=> Tilde MathML representation fix

lib/plurimath/latex/constants.rb, lib/plurimath/latex/parse.rb, lib/plurimath/latex/transform.rb, lib/plurimath/math/function/fenced.rb, lib/plurimath/math/function/left.rb, lib/plurimath/math/function/right.rb, lib/plurimath/utility.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/latex/latexmath_aggregator_spec.rb, spec/plurimath/latex/metanorma_examples_spec.rb, spec/plurimath/latex/parse_spec.rb, spec/plurimath/latex/parser_spec.rb, spec/plurimath/latex_spec.rb, spec/plurimath/math/formula/latex_spec.rb, spec/plurimath/math/function/fenced_spec.rb
This PR adds the following features/fixes.
1. Adds more Left and Right delimiters `\left( ... \right)`.
a. closes #151 
2. Fixes parenthesis misplacement in MathML conversion from LaTex.
a. closes #145
=> Added left right delimiters and latex parser/transformation rules

lib/plurimath/asciimath/transform.rb, lib/plurimath/latex/transform.rb, lib/plurimath/math/function/dot.rb, spec/plurimath/asciimath/parser_spec.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/latex/parser_spec.rb, spec/plurimath/latex_spec.rb, spec/plurimath/math/function/dot_spec.rb, spec/plurimath/mathml/parser_spec.rb
This pull request aims to
1. Enhance the **MathML** conversion process for the **dot** class, ensuring the accurate rendering of **dot** symbols in **MathML** format.
2. It focuses on increasing the code coverage.
closes #155
=> Fixed MathML conversion for dot class and increased code coverage

lib/plurimath/math/formula.rb, lib/plurimath/mathml/parser.rb, spec/plurimath/math/formula/mathml_spec.rb, spec/plurimath/mathml_spec.rb
This PR implements the changes to allow users to explicitly set `displaystyle` attribute's value in **MathML**.
closes #168
=> Added support to allow user to input 'displaystyle' attribute value

lib/plurimath/asciimath/transform.rb, lib/plurimath/math.rb, lib/plurimath/math/formula.rb, lib/plurimath/mathml/parser.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/math_spec.rb
This PR updates **AsciiMath** transformation rules and specs to fix crash on MathML conversion.
closes #175
=> Updates AsciiMath transformation rules

lib/plurimath/math/function/font_style.rb, lib/plurimath/omml/parser.rb, lib/plurimath/omml/transform.rb, lib/plurimath/utility.rb, spec/plurimath/fixtures/expected_values.rb, spec/plurimath/mathml/parser_spec.rb, spec/plurimath/mathml_spec.rb
This PR updates support of fonts for MathML and OMML.
closes #185
=> Fonts support in MathML OMML

Gemfile, lib/plurimath/asciimath/parse.rb, lib/plurimath/asciimath/transform.rb, lib/plurimath/unitsml.rb, spec/plurimath/asciimath/metanorma/mn_samples_bipm_spec.rb, spec/plurimath/asciimath/parser_spec.rb, spec/plurimath/asciimath_spec.rb
This PR implements the following functionality.
1. **Unitsml** parsing and conversion to the **Formula** using **`unitml-ruby`** gem.
a. **Unitsml** syntax is supported in **AsciiMath** input. Then converted to **Plurimath::Formula**.
closes #33 
closes #171
=> Unitsml syntax support in AsciiMath input string

lib/plurimath/math/core.rb, spec/plurimath/fixtures/mathml/line_break/line-break-019.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-024.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-029.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-059.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-061.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-073.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-074.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-075.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-076.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-079.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-081.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-082.mathml, spec/plurimath/fixtures/mathml/line_break/line-break-083.mathml, spec/plurimath/latex_spec.rb
This PR reverts empty tags used in MathML for nil fields.
closes #210
=> Reverting empty tags in MathML

lib/plurimath/unitsml.rb, spec/plurimath/unitsml_spec.rb
This PR adds error raising check for UnitsML equations containing non-numeric values in exponent.
closes #208
=> Added exception for non-numeric exponent value

lib/plurimath/asciimath/parse.rb, lib/plurimath/asciimath/transform.rb, lib/plurimath/math/formula.rb, lib/plurimath/unitsml.rb, spec/plurimath/asciimath/metanorma/mn_samples_bipm_spec.rb, spec/plurimath/asciimath/metanorma/mn_samples_jcgm_spec.rb, spec/plurimath/asciimath/parser_spec.rb, spec/plurimath/asciimath_spec.rb
This PR adds spaces between normal **MathML** tags and  **Unitsml** generated **MathML** as instructed [here](https://github.com/metanorma/bipm-si-brochure/issues/222#issuecomment-1966110260).
closes #222
=> Spaces before Unitsml in MathML

lib/plurimath/unicode_math/transform.rb, spec/plurimath/fixtures/formula_modules/unicode_math_parse_values.rb, spec/plurimath/fixtures/formula_modules/unicode_math_transform_values.rb, spec/plurimath/unicode_math/parser_spec.rb, spec/plurimath/unicode_math/plurimath/unicodemath_tests_spec.rb, spec/plurimath/unicode_math/plurimath/unicodemath_transform_spec.rb, spec/spec_helper.rb
This PR updates parsing and transformation rules related to **UnicodeMath** string's prefixes and suffixes.
closes #224
=> UnicodeMath suffixes and prefixes

lib/plurimath/math/function/log.rb, lib/plurimath/math/function/power_base.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/fixtures/omml/128.omml, spec/plurimath/fixtures/omml/line_break/line-break-061.omml, spec/plurimath/fixtures/omml/line_break/line-break-082.omml, spec/plurimath/fixtures/omml/line_break/line-break-090.omml
This PR removes the **`sub/sup hide`** tags from each tag(**`log`**, **`power_base`**) other than **`nary`**.
Following links explains that the **`SubSupPr`** tags doesn't include **`sub/sup hide`** tags but **`naryPr`** does.
1. **Nary_PR**
a. https://schemas.liquid-technologies.com/officeopenxml/2006/?page=ct_narypr.html
b. http://www.datypic.com/sc/ooxml/e-m_naryPr-1.html
2. **SubSup**
a. https://schemas.liquid-technologies.com/officeopenxml/2006/?page=ct_ssubsup.html
b. http://www.datypic.com/sc/ooxml/e-m_sSubSupPr-1.html
closes #228
=> Fixes broken word rendering

lib/plurimath/asciimath/transform.rb, lib/plurimath/math/formula.rb, lib/plurimath/mathml/transform.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/mathml_spec.rb
This PR updates **MathML** transform rules and Added specs for **AsciiMath** and **MathML**.
closes #238
=> Fixes failing MathML and AsciiMath expression

README.adoc
This PR updates documentation explaining the **Ox** and **Oga** **XML engine**'s support.
closes #245
=> Documentation for XML Engines

lib/plurimath/mathml/parser.rb, lib/plurimath/mathml/transform.rb, lib/plurimath/utility.rb, spec/plurimath/mathml/parser_spec.rb
This PR supports the `intent` attribute from **MathML** elements as input.
=> Intent attribute support in MathML input

lib/plurimath/math/function/fenced.rb, spec/plurimath/asciimath_spec.rb
This PR fixes **Plurimath Fenced** object with `nil` value to **MathML** conversion.
closes #276
=> Fenced object with nil value to MathML conversion fix

plurimath.gemspec
This pull request adds a dependency on **BigDecimal**, as it's a bundled gem starting with `ruby-3.4.0-preview1`.
closes #272
=> Bigdecimal dependency

lib/plurimath/unicode_math/parse.rb, lib/plurimath/unicode_math/parsing_rules/common_rules.rb, lib/plurimath/unicode_math/parsing_rules/sub_sup.rb, lib/plurimath/unicode_math/transform.rb, spec/plurimath/fixtures/formula_modules/unicode_math_string_values.rb, spec/plurimath/fixtures/formula_modules/unicode_math_transform_values.rb, spec/plurimath/unicode_math/parser_spec.rb
This PR updates **UnicodeMath** parsing rules to parse wrapper symbol only string and a string containing wrapper symbols in a complex equation.
=> Unicodemath input wrapper symbols parsed as text 

Rakefile, lib/plurimath/formatter/numeric_formatter.rb, lib/plurimath/math/core.rb, lib/plurimath/math/formula.rb, lib/plurimath/math/function/fenced.rb, lib/plurimath/math/function/frac.rb, lib/plurimath/math/symbols/symbol.rb, lib/plurimath/setup/opal.rb.erb, lib/plurimath/unicode_math/constants.rb, lib/plurimath/unicode_math/parser.rb, lib/plurimath/utility.rb, spec/spec_helper.rb
This PR changes
1. `gsub!` to `gsub`
2. `strip!` to `strip`
3. `sub!` to `sub`
4. Added `\` for parenthesis in regex.
Also required `symbols` and `parens` classes for opal and updated related code.
=> Plurimath-JS build fixes

lib/plurimath/math/formula.rb, lib/plurimath/unitsml.rb, spec/plurimath/math/formula/unitsml_spec.rb
This PR introduces a new boolean argument called `unitsml_xml` in the `to_mathml` method for **MathML** conversion. This argument provides optional support for **UnitsML** in the **MathML** conversion.
closes #297
=> Unitsml semantics in MathML output

lib/plurimath/mathml/transform.rb, spec/plurimath/mathml/parser_spec.rb
This PR updates transformation rules for **MathML** conversion of `"."` from **Period**(**Symbol**) to **Dot**(**Function**).
closes #299
=> Updated transformation rule for dot class

lib/plurimath/math/symbols/gg.rb, lib/plurimath/math/symbols/ll.rb, spec/plurimath/asciimath/asciidoctor_examples_spec.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/math/symbols/gg_spec.rb, spec/plurimath/math/symbols/ll_spec.rb
This PR supports the **much greater than** and **much less than** signs **AsciiMath** parsing and conversion.
closes #308
=> `mgt` and `mlt` support in AsciiMath

lib/plurimath/math/formula.rb, spec/plurimath/math/formula_spec.rb
This PR updates the error message for the un-supported `to_display` type.
closes #310
=> Added `type_error` method in Formula

lib/plurimath/math/formula.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/math/formula/unitsml_spec.rb
This PR inserts `thickmathspace` before each unitsml example.
closes #314
=> `thickmathspace` before every `unitsml`

lib/plurimath/math/symbols/symbol.rb, spec/plurimath/mathml_spec.rb
This PR fixes the empty `mo` tag to **OMML** conversion.
close #318
=> empty `mo` tag to OMML conversion

lib/plurimath/math/function/msgroup.rb, spec/plurimath/omml_spec.rb, spec/spec_helper.rb
This PR updates **MathML** parsing methods and specs for **Oga** adapter support.
related to plurimath/plurimath-js#28
=> MathML parsing using Oga

lib/plurimath/math/function/bar.rb, lib/plurimath/mathml/constants.rb, lib/plurimath/omml/parser.rb, spec/plurimath/fixtures/formula_modules/expected_values.rb, spec/plurimath/fixtures/omml/122.omml, spec/plurimath/fixtures/omml/124.omml, spec/plurimath/fixtures/omml/125.omml, spec/plurimath/fixtures/omml/126.omml, spec/plurimath/mathml/v3/section_3_spec.rb, spec/plurimath/omml_spec.rb
This PR fixes **OMML** parsing error for `overline` and the `comments`.
closes #324
=> OMML `overline` and `comment` parsing error

lib/plurimath/math/symbols/symbol.rb, spec/plurimath/fixtures/formula_modules/expected_values.rb, spec/plurimath/fixtures/omml/188.omml, spec/plurimath/math/formula/omml_spec.rb
This PR temporarily skips invisible-times: `&#x2062;` conversion to **OMML**.
closes #312
=> Stripping `invisible times` for OMML conversion

lib/plurimath/math/formula.rb, lib/plurimath/mathml/parser.rb
This PR moves the `Mml` configuration from the method to the file's top level.
Add the `display` attribute's methods (added in `mml`) in `formula.rb`.
related => plurimath/mml#4
=> Updated `mml` configuration and added `display` methods

lib/plurimath/math/function/root.rb, lib/plurimath/omml/transform.rb, spec/plurimath/fixtures/formula_modules/expected_values.rb
This PR updates the transformation rules and specs to fix the **OMML** conversion of radicals.
closes #333
=> Fix for incorrect parsing of radicals in OMML

lib/plurimath/math/formula.rb, lib/plurimath/math/formula/mrow.rb, lib/plurimath/math/function/fenced.rb, lib/plurimath/math/function/none.rb, lib/plurimath/math/function/underset.rb, lib/plurimath/math/symbols/symbol.rb, lib/plurimath/mathml/parser.rb, lib/plurimath/mathml/utility.rb, lib/plurimath/mathml/utility/formula_transformation.rb, spec/plurimath/mathml/parser_spec.rb, spec/plurimath/omml_spec.rb
This PR implements changes related to the latest version `0.6.0` of the lutaml-model(at the time of implementation).
Also updated the **Mml** configuration syntax for **MathML** parsing.
=> Updated internal use of `element_order` and Mml configuration

Gemfile, plurimath.gemspec
This PR adds the `Unitsml-Ruby` gem as a `dependency` in the `gemspec` file.
closes #335
=> Unitsml-Ruby added as dependency

.github/workflows/dependent-repos.json, .github/workflows/dependent-tests.yml, lib/plurimath/math/core.rb, lib/plurimath/math/formula.rb, lib/plurimath/math/function/fenced.rb, lib/plurimath/math/function/ms.rb
This PR updates the **MathML** parsing methods and fixes failing specs.
related to => **metanorma/iso-10303#459**
=> LutaML-Model version `0.7.1` compatibility

lib/plurimath.rb, lib/plurimath/asciimath/parse.rb, lib/plurimath/asciimath/transform.rb, spec/plurimath/asciimath_spec.rb
This PR updates the **parsing** and **transformation** rules (**parslet**) for **AsciiMath** to support **matrix** (table) encoding with **powerbase**.
closes #351
closes #354
=> Fix: AsciiMath encoding matrix with powerbase

lib/plurimath/latex/transform.rb, spec/plurimath/latex_spec.rb
This PR adds a transformation rule for **LaTeX** and spec.
closes #355
=> Fix: LaTeX transformation rule

lib/plurimath/formatter/numbers/fraction.rb, spec/plurimath/number_formatter_spec.rb
This PR fixes the `digit_count` behavior.
closes #360
=> Fix: `digit_count` behaviour

lib/plurimath/math/formula.rb, lib/plurimath/math/function/unary_function.rb, spec/plurimath/asciimath_spec.rb
This PR inserts a space element before standard Unary functions (`sin`, `cos`, `tan`, etc) based on an optional boolean argument `unary_function_spacing`.
Screenshot attachment from PDF presentation.
closes #352
=> Added thick math space before standard unary functions

lib/plurimath/formatter/numbers/significant.rb, spec/plurimath/number_formatter_spec.rb
This PR updates the behaviour of `significant` options passed inside `format` hash for number formatting.
```ruby
> Plurimath::NumberFormatter.new(:en).localized_number("0.0082", format: { significant: 4 })
=> "0.008200" # adding significant zeros to meet the significant number passed.
```
```ruby
> Plurimath::NumberFormatter.new(:en).localized_number("0.0082", format: { significant: 4 })
=> "0.0082" # If the value of the `significant` option exceeds the given number, then truncate the number; otherwise, do nothing.
```
closes #363
=> Update: Significant digits

lib/plurimath/math/formula.rb, spec/plurimath/asciimath_spec.rb, spec/plurimath/latex_spec.rb, spec/plurimath/math/formula/intent_encoding_spec.rb, spec/plurimath/math/formula/mathml_spec.rb, spec/plurimath/math/formula_spec.rb, spec/plurimath/math_zone_spec.rb, spec/plurimath/mathml/line_breaks_spec.rb, spec/plurimath/mathml_spec.rb
This PR updates the default value of `unary_function_spacing` from `false` to `true`.
Additionally, some syntax-related changes.
related to #362
=> Updated `unary_function_spacing` argument default value to true

lib/plurimath/math/symbols/approx.rb, spec/plurimath/math/symbols/approx_spec.rb, spec/plurimath/mathml_spec.rb
This PR updates the approx symbol `&#x2248;` output in **MathML**.
closes #372
=> Updated approx symbol's MathML output

lib/plurimath/math/formula.rb, lib/plurimath/math/function/td.rb, lib/plurimath/math/symbols/comma.rb, spec/plurimath/math/symbols/comma_spec.rb
This PR updates the comma handling in **AsciiMath**’s matrix conversion.
closes #376
=> Commas in matrices conversion of AsciiMath
